//next js
import Head from "next/head"
import Image from "next/image"
import Link from "next/link"
import { useRouter } from "next/router"

//style modBoxe
import styles from "../styles/Home.module.css"

//material-ui
import {
  Box,
  Grid,
  Typography,
  Paper,
  IconButton,
  Avatar,
  AppBar,
  Toolbar,
  Button
} from "@mui/material"

export default function Home() {
  const router = useRouter()

  return (
    <>
      <Head>
        <title>Sunnyside</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box component="div" className="container">
        <Box component="header" sx={{ backgroundColor: "#3dbeff" }}>
          <AppBar
            sx={{ mb: 3, boxShadow: "0px 0px 0px rgb(0, 0, 0, 0)" }}
            position="relative"
          >
            <Toolbar>
              <Typography
                variant="h2"
                component="h4"
                sx={{
                  flexGrow: 1,
                  fontWeight: "bold",
                  fontSize: { xs: "4vw", sm: "3vw", md: "2vw" },
                  letterSpacing: { xs: "5px" },
                }}
              >
                sunnyside
              </Typography>

              <Box component="ul" sx={{listStyle: 'none', display: {xs: 'none', md: 'flex'}, flexDirection: 'row', alignItems: 'center'}}>
                <Box component="li" sx={{mr: 3}}>
                  <Typography variant="h5" component="h4" sx={{fontSize: {sm: "1.5vw", md: "1vw" }, opacity: "0.5", fontWeight: "700", letterSpacing: { sm: "5px" },}}>
                    <Link href="#"><a>About</a></Link>
                  </Typography>
                </Box>               
                <Box component="li" sx={{mr: 3}}>
                  <Typography variant="h5" component="h4" sx={{fontSize: {sm: "1.5vw", md: "1vw" }, opacity: "0.5", fontWeight: "700", letterSpacing: { sm: "5px" },}}>
                    <Link href="#"><a>Services</a></Link>
                  </Typography>
                </Box>               
                <Box component="li" sx={{mr: 3}}>
                  <Typography variant="h5" component="h4" sx={{fontSize: {sm: "1.5vw", md: "1vw" }, opacity: "0.5", fontWeight: "700", letterSpacing: { sm: "5px" },}}>
                    <Link href="#"><a>Projects</a></Link>
                  </Typography>
                </Box>               
                <Box component="li" sx={{mr: 3}}>
                  <Button sx={{borderRadius: '10px' , backgrondColor: 'white', color: 'black'}}>Contact</Button>
                </Box>               
              </Box>

              <IconButton sx={{display: {xs: 'block', md: "none"}}}>
                <Box                
                  component="svg"
                  sx={{
                    weight: { xs: "3.5vw", sm: "3vw", md: "2vw" },                    
                    height: { xs: "3.5vw", sm: "3vw", md: "2vw" },                    
                  }}
                  xmlns="http://www.w3.org/2000/svg"                  
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M4 6h16M4 12h16M4 18h16"
                  />
                </Box>
              </IconButton>
            </Toolbar>
          </AppBar>

          <Typography
            variant="h1"
            align="center"
            sx={{
              letterSpacing: "5px",
              fontSize: { xs: "12vw" },
              color: "white",
              fontWeight: "bold",
            }}
          >
            WE ARE CREATIVES
          </Typography>
          <Box
            component="img"
            src="/image-header.jpg"
            alt=""
            sx={{ maxWidth: "100%" }}
          />
        </Box>

        <Box component="main">
          <Grid container sx={{mb: 3}}>
            <Grid item xs={12} sm={6} sx={{ py: 2, backgroundColor: "white" }}>
              <Paper sx={{ p: 2, py: 4 }} elevation={0}>
                <Typography
                  variant="h2"
                  align="center"
                  sx={{
                    mx: "auto",
                    mb: 5,
                    fontSize: { xs: "9vw", sm: "5vw", md: "3vw" },
                    fontWeight: "bold",
                    maxWidth: { md: "60%" },
                  }}
                >
                  Transform your brand
                </Typography>
                <Typography
                  variant="body1"
                  align="center"
                  sx={{
                    mb: 3,
                    fontSize: { xs: "4vw", sm: "1.5vw", md: "1.5vw" },
                    opacity: "0.8",
                  }}
                >
                  We are a fBoxl-service creative agency specializing in helping
                  brands grow fast. Engage your clients through compelling
                  visuals that do most of the marketing for you.
                </Typography>
                <Typography
                  variant="h6"
                  align="center"
                  sx={{
                    mx: "auto",
                    mb: 5,
                    fontSize: { xs: "4vw", sm: "3vw", md: "2vw" },
                    fontWeight: "bold",
                    maxWidth: { md: "60%" },
                  }}
                >
                      <Link href="# "> 
                        <a>Learn more</a>                  
                      </Link>                  
                </Typography>
              </Paper>  
            </Grid>
            <Grid item xs={12} sm={6} sx={{ backgroundColor: "#ffd300" }}>
              <Box
                component="img"
                src="/image-transform.jpg"
                alt=""
                sx={{ maxWidth: "100%" }}
              />
            </Grid>
            <Grid item xs={12} sm={6}>
              <Box
                component="img"
                src="/image-stand-out.jpg"
                alt=""
                sx={{ maxWidth: "100%" }}
              />    
            </Grid>
            <Grid item xs={12} sm={6} sx={{ py: 2, backgroundColor: "white" }}>
              <Paper sx={{ p: 2, py: 4 }} elevation={0}>
                <Typography
                  variant="h2"
                  align="center"
                  sx={{
                    mx: "auto",
                    mb: 5,
                    fontSize: { xs: "9vw", sm: "4vw", md: "3vw" },
                    fontWeight: "bold",
                    maxWidth: { md: "80%" },
                  }}
                >
                  Stand out to the right audience
                </Typography>
                <Typography
                  variant="body1"
                  align="center"
                  sx={{
                    mb: 3,
                    fontSize: { xs: "4vw", sm: "1.5vw", md: "1.5vw" },
                    opacity: "0.8",
                  }}
                >
                  We are a fBoxl-service creative agency specializing in helping
                  brands grow fast. Engage your clients through compelling
                  visuals that do most of the marketing for you.
                </Typography>
                <Typography
                  variant="h6"
                  align="center"
                  sx={{
                    mx: "auto",
                    mb: 5,
                    fontSize: { xs: "4vw", sm: "3vw", md: "2vw" },
                    fontWeight: "bold",
                    maxWidth: { md: "60%" },
                  }}
                >
                  <Link href="# "> 
                    <a>Learn more</a>                  
                  </Link> 
                </Typography>
              </Paper>
            </Grid>
            <Grid
              item
              xs={12}
              sm={6}
              //sx={{backgroundColor: '#8ed5c7'}}
            >
              <Box
                component="img"
                src="/image-graphic-design.jpg"
                alt=""
                sx={{ maxWidth: "100%" }}
              />
            </Grid>
            <Grid item xs={12} sm={6} sx={{position: 'relative'}}>
              <Box
                component="img"
                src="/image-photography.jpg"
                alt=""
                sx={{ maxWidth: "100%"}}
              />   
                      
            </Grid>
          </Grid>

          <Grid
            container
            justifyContent="center"
            className="testimonial"
            sx={{ p: 2, height: "auto" }}
          >
            <Grid item xs={12} sx={{ p: 4 }}>
              <Typography
                variant="h2"
                align="center"
                sx={{
                  mx: "auto",
                  mb: 3,
                  p: 2,
                  fontSize: { xs: "4vw", sm: "2vw", md: "3vw" },                  
                  maxWidth: { md: "50vw" },
                  letterSpacing: '5px',
                }}
              >
                CLIENT TESTIMONIALS
              </Typography>
            </Grid>

            <Grid
              container
              spacing={2}
              justifyContent="center"
              className="testimonial"
              sx={{ height: "auto" }}
            >
              <Grid
                item
                xs={12}
                sm={4}
                sx={{ p: 2, mb: 5}}
              >
                <Paper
                  sx={{
                    mx: "auto",
                    p: 2,
                    py: 4,
                    display: "flex",
                    flexDirection: "column",
                    alignItems: "center",
                    justifyContent: "center",
                    boxShadow: "3px 6px 1rem rgb(0, 0, 0, .3)",
                    backgroundColor: "whiteSmoke",
                  }}
                  elevation={0}
                >
                  <Avatar sx={{ mb: 3 }}></Avatar>

                  <Typography
                    variant="body1"
                    sx={{
                      mb: 2,
                      fontSize: { xs: "4vw", sm: "1.5vw" },
                      opacity: "0.6",
                    }}
                  >
                    We put our trust in Sunnyside and they delivered, making
                    sure our needs were met deadlines were always hit.
                  </Typography>
                  <Typography
                    variant="h4"
                    sx={{ mb: 2, fontSize: { xs: "7vw", sm: "3vw" } }}
                  >
                    Emily R.
                  </Typography>
                  <Typography
                    variant="h6"
                    sx={{
                      fontWeight: "lighter",
                      opacity: "0.5",
                      fontSize: { xs: "4vw", sm: "1.5vw" },
                    }}
                  >
                    Marketing Director
                  </Typography>
                </Paper>
              </Grid>
              <Grid
                item
                xs={12}
                sm={4}
                sx={{ p: 2, mb: 5, backgroundColor: "white" }}
              >
                <Paper
                  sx={{
                    mx: "auto",
                    p: 2,
                    py: 4,
                    display: "flex",
                    flexDirection: "column",
                    alignItems: "center",
                    justifyContent: "center",
                    boxShadow: "3px 6px 1rem rgb(0, 0, 0, .3)",
                  }}
                  elevation={0}
                >
                  <Avatar sx={{ mb: 3 }}></Avatar>

                  <Typography
                    variant="body1"
                    sx={{
                      mb: 2,
                      fontSize: { xs: "4vw", sm: "1.5vw" },
                      opacity: "0.6",
                    }}
                  >
                    Sunnysides enthusiasm coupled with their keen interest in
                    our brands success made it satisfying and enjoyable
                    experience
                  </Typography>
                  <Typography
                    variant="h4"
                    sx={{ mb: 2, fontSize: { xs: "7vw", sm: "3vw" } }}
                  >
                    {" "}
                    Thomas S.{" "}
                  </Typography>
                  <Typography
                    variant="h6"
                    sx={{
                      fontWeight: "lighter",
                      opacity: "0.5",
                      fontSize: { xs: "4vw", sm: "1.5vw" },
                    }}
                  >
                    Chef Operations Officer
                  </Typography>
                </Paper>
              </Grid>
              <Grid
                item
                xs={12}
                sm={4}
                sx={{ p: 5, mb: 5, backgroundColor: "white" }}
              >
                <Paper
                  sx={{
                    mx: "auto",
                    p: 2,
                    py: 4,
                    display: "flex",
                    flexDirection: "column",
                    alignItems: "center",
                    justifyContent: "center",
                    boxShadow: "3px 6px 1rem rgb(0, 0, 0, .3)",
                  }}
                  elevation={0}
                >
                  <Avatar sx={{ mb: 3 }}></Avatar>

                  <Typography
                    variant="body1"
                    sx={{
                      mb: 2,
                      fontSize: { xs: "4vw", sm: "1.5vw" },
                      opacity: "0.6",
                    }}
                  >
                    Incredible end resBoxt! Our sales increased over 400% when we
                    worked with Sunnyside. Highly recommended!
                  </Typography>
                  <Typography
                    variant="h4"
                    sx={{ mb: 2, fontSize: { xs: "7vw", sm: "3vw" } }}
                  >
                    Jennie F.
                  </Typography>
                  <Typography
                    variant="h6"
                    sx={{
                      fontWeight: "lighter",
                      opacity: "0.5",
                      fontSize: { xs: "4vw", sm: "1.5vw" },
                    }}
                  >
                    Business Owner
                  </Typography>
                </Paper>
              </Grid>
            </Grid>
          </Grid>

          <Grid container className="imageGallery">
            <Grid item xs={6} sm={3}>
              <Box
                component="img"
                src="/image-gallery-milkbottles.jpg"
                alt=""
                sx={{ maxWidth: "100%" }}
              />
            </Grid>
            <Grid item xs={6} sm={3}>
              <Box
                component="img"
                src="/image-gallery-orange.jpg"
                alt=""
                sx={{ maxWidth: "100%" }}
              />
            </Grid>
            <Grid item xs={6} sm={3}>
              <Box
                component="img"
                src="/image-gallery-cone.jpg"
                alt=""
                sx={{ maxWidth: "100%" }}
              />
            </Grid>
            <Grid item xs={6} sm={3}>
              <Box
                component="img"
                src="/image-gallery-sugarcubes.jpg"
                alt=""
                sx={{ m: 0, maxWidth: "100%" }}
              />
            </Grid>
          </Grid>
        </Box>

        <Grid
          container
          sx={{ p: 2, backgroundColor: "rgb(235,126,121)" }}
          className="footer"
          direction="row"
          alignItems="center"
          justifyContent="center"
        >
          <Grid item xs={12} sm={4}>
            <Paper
              sx={{ p: 2, backgroundColor: "rgb(235,126,121)" }}
              elevation={0}
            >
              <Typography
                variant="h5"
                align="center"
                sx={{ fontWeight: "bold", opacity: "0.7", mb: 3 }}
              >
                sunnyside
              </Typography>

              <Grid
                container
                spacing={2}
                className="footerNavLinks"
                sx={{ mb: 3 }}
                direction="row"
                alignItems="center"
                justifyContent="center"
              >
                <Grid item>
                  <Link passHref href="#">
                    <Box component="a">About</Box>
                  </Link>
                </Grid>
                <Grid item>
                  <Link passHref href="#">
                    <Box component="a">Services</Box>
                  </Link>
                </Grid>
                <Grid item>
                  <Link passHreff href="#">
                    <Box component="a">Products</Box>
                  </Link>
                </Grid>
              </Grid>

              <Grid
                container
                spacing={2}
                className="footerSocialMediaLinksd"
                sx={{ mb: 3 }}
                direction="row"
                alignItems="center"
                justifyContent="center"
              >
                <Grid item>
                  <Link passHref href="#">
                    <Box component="a">Instagram</Box>
                  </Link>
                </Grid>
                <Grid item>
                  <Link passHref href="#">
                    <Box component="a">Twitter</Box>
                  </Link>
                </Grid>
                <Grid item>
                  <Link passHref href="#">
                    <Box component="a">Facebook</Box>
                  </Link>
                </Grid>
              </Grid>
            </Paper>
          </Grid>
        </Grid>
      </Box>
    </>
  )
}
